### ISSUE TITLE
Can not start on Mac OSX:  Invalid thread access

### ISSUE THREAD

**Issue by valerytschopp** [udoprog/c10t-swt#1]
$ java -jar target/c10t-swt-macosx-cocoa-x86_64-jar-with-dependencies.jar 
***WARNING: Display must be created on main thread due to Cocoa restrictions.
Exception in thread "main" org.eclipse.swt.SWTException: Invalid thread access
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.widgets.Display.error(Unknown Source)
    at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
    at org.eclipse.swt.widgets.Display.create(Unknown Source)
    at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
    at org.eclipse.swt.widgets.Display.getDefault(Unknown Source)
    at eu.toolchain.c10t.Main.main(Main.java:102)

**Comment by udoprog** [comment]
add -XstartOnFirstThread as an java option

**Comment by valerytschopp** [comment]
Yeap, it solve the starting issue. Thanks
